/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Name.h
 #	source generated by 4D Plugin Wizard
 #	Project : Name
 #	author : miyako
 #	2025/07/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NAME_H
#define PLUGIN_NAME_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

#if VERSIONWIN
#include <windows.h>
#include <commctrl.h>
#include <shlobj.h>
#include <shlwapi.h>
#include <shobjidl.h>
#include <commctrl.h>
#include <shellapi.h>
#include <initguid.h> // for DEFINE_GUID
#include <gdiplus.h>
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "gdiplus.lib")
#pragma comment(lib, "shell32.lib")
struct IImageListVtbl;
struct IImageList {
    IImageListVtbl* lpVtbl;
};
struct IImageListVtbl {
    HRESULT(STDMETHODCALLTYPE* QueryInterface)(IImageList*, REFIID, void**);
    ULONG(STDMETHODCALLTYPE* AddRef)(IImageList*);
    ULONG(STDMETHODCALLTYPE* Release)(IImageList*);
    HRESULT(STDMETHODCALLTYPE* Add)(IImageList*, HBITMAP, HBITMAP, int*);
    HRESULT(STDMETHODCALLTYPE* ReplaceIcon)(IImageList*, int, HICON, int*);
    HRESULT(STDMETHODCALLTYPE* SetOverlayImage)(IImageList*, int, int);
    HRESULT(STDMETHODCALLTYPE* Replace)(IImageList*, int, HBITMAP, HBITMAP);
    HRESULT(STDMETHODCALLTYPE* AddMasked)(IImageList*, HBITMAP, COLORREF, int*);
    HRESULT(STDMETHODCALLTYPE* Draw)(IImageList*, IMAGELISTDRAWPARAMS*);
    HRESULT(STDMETHODCALLTYPE* Remove)(IImageList*, int);
    HRESULT(STDMETHODCALLTYPE* GetIcon)(IImageList*, int, UINT, HICON*);
    // Other methods omitted for brevity
};
#endif

#pragma mark -

void Get_localized_name(PA_PluginParameters params);

typedef enum {
    object_class_none   = 0,
    object_class_file   = 1,
    object_class_folder = 2
} object_class_t;

static object_class_t _ob_class(PA_ObjectRef f);
static bool _object_to_path(PA_ObjectRef f, std::string& path, int type);
static bool file_object_to_path(PA_ObjectRef f, std::string& path);
static bool folder_object_to_path(PA_ObjectRef f, std::string& path);
static void set_object_property(PA_ObjectRef o, const char *key, PA_Variable value);

#endif /* PLUGIN_NAME_H */
