/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Name.h
 #	source generated by 4D Plugin Wizard
 #	Project : Name
 #	author : miyako
 #	2025/07/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NAME_H
#define PLUGIN_NAME_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

#if VERSIONWIN
#include <windows.h>
#include <commctrl.h>
#include <shlobj.h>
#include <shlwapi.h>
#include <shobjidl.h>
#include <commctrl.h>
#include <shellapi.h>
#include <gdiplus.h>
#include <commoncontrols.h> // official IImageList interface (replaces the hand-rolled vtable mirror below)
#include <mutex>
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "gdiplus.lib")
#pragma comment(lib, "shell32.lib")
// NOTE: the previous hand-rolled `IImageList`/`IImageListVtbl` structs (a partial, hand-ordered
// vtable mirror) were removed in favor of <commoncontrols.h>'s official declaration, which is
// the complete, correctly-ordered interface and IID_IImageList as maintained by the Windows SDK.
// A hand-rolled partial vtable is only safe as long as no method used comes after an omitted one
// in the real interface's declared order -- that held true here, but is fragile against any future
// SDK/Windows revision and can't be verified by inspection alone.
#endif

#pragma mark -

void Get_localized_name(PA_PluginParameters params);

typedef enum {
    object_class_none   = 0,
    object_class_file   = 1,
    object_class_folder = 2
} object_class_t;

static object_class_t _ob_class(PA_ObjectRef f);
static bool _object_to_path(PA_ObjectRef f, std::string& path, int type);
static bool file_object_to_path(PA_ObjectRef f, std::string& path);
static bool folder_object_to_path(PA_ObjectRef f, std::string& path);
static void set_object_property(PA_ObjectRef o, const char *key, PA_Variable value);

#endif /* PLUGIN_NAME_H */
