/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Name.h
 #	source generated by 4D Plugin Wizard
 #	Project : Name
 #	author : miyako
 #	2025/07/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NAME_H
#define PLUGIN_NAME_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

#if VERSIONWIN
#include <windows.h>
#include <shlwapi.h>
#include <shellapi.h>
#include <shobjidl.h>
#endif

#pragma mark -

void Get_localized_name(PA_PluginParameters params);

typedef enum {
    object_class_none   = 0,
    object_class_file   = 1,
    object_class_folder = 2
} object_class_t;

static object_class_t _ob_class(PA_ObjectRef f);
static bool _object_to_path(PA_ObjectRef f, std::string& path, int type);
static bool file_object_to_path(PA_ObjectRef f, std::string& path);
static bool folder_object_to_path(PA_ObjectRef f, std::string& path);
static void set_object_property(PA_ObjectRef o, const char *key, PA_Variable value);

#endif /* PLUGIN_NAME_H */
